kind = "web"
previewPath = "/"
title = "AudixMusic"
version = "1.0.0"
id = "artifacts/audix"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/", "/api/subscribe" ]
localPort = 24881

[services.development]
run = "pnpm --filter @workspace/audix run dev"

[services.env]
PORT = "24881"

[services.production.build]
args = [ "pnpm", "--filter", "@workspace/audix", "run", "build" ]

[services.production.run]
args = [ "pnpm", "--filter", "@workspace/audix", "run", "start" ]

[services.production.run.env]
PORT = "24881"
NODE_ENV = "production"
